repos:
  - repo: local
    hooks:
      - id: run-black
        name: Run Black
        entry: ./scripts/run_black.sh
        language: system
        pass_filenames: false

      - id: run-pylint
        name: Run Pylint
        entry: ./scripts/run_pylint.sh
        language: system
        pass_filenames: false

      - id: format-yaml
        name: Format YAML Files
        entry: yamlfmt
        language: python
        types: [yaml]
        files: \.(yml|yaml)$

      - id: rust-check
        name: Check Rust Code
        entry: ./scripts/check_rust.sh
        language: rust
